#  Copyright 2018 1Strategy, LLC

#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at

#        http://www.apache.org/licenses/LICENSE-2.0

#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'This CloudFormation script provisions a RDS instance(s). '


Parameters:
  AllocatedStorage:
    Description: The allocated storage size, specified in gigabytes (GB).
    Type: String
    AllowedPattern: "^([2-9]?[0-9]{1}|[0-9]{3,4}|1[0-5]?[0-9]{3}|16[0-2]?[0-9]{2}|163[0-7]?[0-9]{1}|1638[0-4]?)$"
    ConstraintDescription: "For SQL Server Express or Web Edition, the value must be a valid number between 20-16384. For SQL Server Standard or Enteprise editions, the value must be a valid number between 200 and 16384"
  
  AllowMajorVersionUpgrade:
    Description: If you update the EngineVersion property to a version that's different from the DB instance's current major version, set this property to true.
    Type: String
    AllowedValues: [true, false]
    ConstraintDescription: "Value must be boolean value."

  AutoMinorVersionUpgrade:
    Description: Indicates that minor engine upgrades are applied automatically to the DB instance during the maintenance window. The default value is true.
    Type: String
    AllowedValues: [true, false]
    Default: true
    ConstraintDescription: "Value must be boolean value."
  
  BackupRetentionPeriod:
    Description: The number of days during which automatic DB snapshots are retained.
    Type: String
    AllowedPattern: "^([0-9]{1}|[1-2]{1}[0-9]{1}|3[0-5]{1})$"
    ConstraintDescription: "Value must be a valid number between 0-35."

  DBInstanceClass:
    Description: The name of the compute and memory capacity classes of the DB instance.
    Type: String
    Default: db.t2.medium
    
  Engine:
    Description: The name of the database engine to be used for this instance.
    Type: String
    AllowedValues: [sqlserver-ee, sqlserver-se, sqlserver-ex, sqlserver-web]
    ConstraintDescription: "Please specify either a sqlserver-ee, sqlserver-se, sqlserver-ex, or sqlserver-web engine for the RDS instance."

  DBSubnetGroupName:
    Description: A DB subnet group to associate with the DB instance. 
    Type: String
  
  VPCSecurityGroups:
    Description: Specifies if the database instance is a multiple Availability Zone deployment.
    Type: List<AWS::EC2::SecurityGroup::Id>
    ConstraintDescription: "Please provide valid ids for the security group(s)."

  MasterUsername:
    Description: The master user name for the DB instance.
    Type: String

  MasterUserPassword:
    Description: The master password for the DB instance.
    Type: String
    NoEcho: true
  
  MultiAZ:
    Description: Specifies if the database instance is a multiple Availability Zone deployment.
    Type: String
    AllowedValues: [true, false]
    Default: true
    ConstraintDescription: "Value must be boolean value."

Conditions: 
  CreateSQLServerEnterpriseOrStandardResources: !Or  [!Equals [ !Ref Engine ,  sqlserver-ee], !Equals [ !Ref Engine ,  sqlserver-se]]
  CreateSQLServerExpressOrWebResources: !Not [!Or  [!Equals [ !Ref Engine ,  sqlserver-ee], !Equals [ !Ref Engine ,  sqlserver-se]]]
Resources:  
  SQLServerInstanceHigherEditions:
    Type: "AWS::RDS::DBInstance"
    Condition: CreateSQLServerEnterpriseOrStandardResources
    Properties:
      AllocatedStorage: !Ref AllocatedStorage
      AllowMajorVersionUpgrade: !Ref AllowMajorVersionUpgrade
      AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
      BackupRetentionPeriod:  !Ref BackupRetentionPeriod
      CopyTagsToSnapshot: true
      DBInstanceClass: !Ref DBInstanceClass
      Engine: !Ref Engine
      LicenseModel: license-included
      DBSubnetGroupName: !Ref DBSubnetGroupName
      VPCSecurityGroups: !Ref VPCSecurityGroups
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      MultiAZ: !Ref MultiAZ
      MonitoringInterval: 0 #Not using enhanced monitoring. Regular RDS monitoring is still enabled.
      PubliclyAccessible: false 
      StorageType: gp2
      Tags:
        - Key: Name
          Value: !Sub
            - ${AWS::StackName}-${Name}
            - { Name: !Ref Engine }
 
  SQLServerInstanceLowerEditions:
    Type: "AWS::RDS::DBInstance"
    Condition: CreateSQLServerExpressOrWebResources
    Properties:
      AllocatedStorage: !Ref AllocatedStorage
      AllowMajorVersionUpgrade: !Ref AllowMajorVersionUpgrade
      AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
      BackupRetentionPeriod:  !Ref BackupRetentionPeriod
      CopyTagsToSnapshot: true
      DBInstanceClass: !Ref DBInstanceClass
      Engine: !Ref Engine
      LicenseModel: license-included
      DBSubnetGroupName: !Ref DBSubnetGroupName
      VPCSecurityGroups: !Ref VPCSecurityGroups
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      MonitoringInterval: 0 #Not using enhanced monitoring. Regular RDS monitoring is still enabled.
      PubliclyAccessible: false 
      StorageType: gp2
      Tags:
        - Key: Name
          Value: !Sub
            - ${AWS::StackName}-${Name}
            - { Name: !Ref Engine }



Outputs:
  DBInstanceIdentifierHigherEditions:
    Description: The database instance identifier
    Value: !Ref SQLServerInstanceHigherEditions
    Condition: CreateSQLServerEnterpriseOrStandardResources
    Export:
      Name: !Sub 
      - "${AWS::StackName}-${engine}-identifier"
      - {engine: !Ref Engine }

  DBEndpointHigherEditions:
    Description: The connection endpoint for the database.
    Value: !GetAtt  SQLServerInstanceHigherEditions.Endpoint.Address
    Condition: CreateSQLServerEnterpriseOrStandardResources
    Export:
      Name: !Sub 
        - "${AWS::StackName}-${engine}-endpoint"
        - {engine: !Ref Engine }

  DBPortHigherEditions:
    Description: The port number on which the database accepts connections.
    Value: !GetAtt  SQLServerInstanceHigherEditions.Endpoint.Port
    Condition: CreateSQLServerEnterpriseOrStandardResources
    Export:
      Name: !Sub 
        - "${AWS::StackName}-${engine}-port"
        - {engine: !Ref Engine }

  DBInstanceIdentifierLowerEditions:
    Description: The database instance identifier
    Value: !Ref SQLServerInstanceLowerEditions
    Condition: CreateSQLServerExpressOrWebResources
    Export:
      Name: !Sub 
      - "${AWS::StackName}-${engine}-identifier"
      - {engine: !Ref Engine }

  DBEndpointLowerEditions:
    Description: The connection endpoint for the database.
    Value: !GetAtt  SQLServerInstanceLowerEditions.Endpoint.Address
    Condition: CreateSQLServerExpressOrWebResources
    Export:
      Name: !Sub 
        - "${AWS::StackName}-${engine}-endpoint"
        - {engine: !Ref Engine }

  DBPortLowerEditions:
    Description: The port number on which the database accepts connections.
    Value: !GetAtt  SQLServerInstanceLowerEditions.Endpoint.Port
    Condition: CreateSQLServerExpressOrWebResources
    Export:
      Name: !Sub 
        - "${AWS::StackName}-${engine}-port"
        - {engine: !Ref Engine }



